-- Database Table Creation Script
-- Created: <%= DateTime.Now.ToString("yyyy-MM-dd") %>
-- For: Online Pastry Shop (Ocakes)
-- Username: Aaron_IPT
-- Password: qwen123

-- Drop existing tables if needed (uncomment if you want to recreate tables)
/*
DROP TABLE "AARON_IPT"."ORDERDETAILS";
DROP TABLE "AARON_IPT"."PRODUCTCATEGORIES";
DROP TABLE "AARON_IPT"."ORDERS";
DROP TABLE "AARON_IPT"."PRODUCTS";
DROP TABLE "AARON_IPT"."CATEGORIES";
DROP TABLE "AARON_IPT"."USERS";
*/

-- Create CATEGORIES table
CREATE TABLE "AARON_IPT"."CATEGORIES" 
(
    "CATEGORYID" NUMBER(*,0), 
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
    "DESCRIPTION" VARCHAR2(4000 BYTE), 
    "PARENTCATEGORYID" NUMBER(*,0), 
    "DATECREATED" DATE DEFAULT SYSDATE, 
    "DATEMODIFIED" DATE DEFAULT SYSDATE, 
    "ISACTIVE" NUMBER(1,0) DEFAULT 1, 
    PRIMARY KEY ("CATEGORYID") ENABLE, 
    UNIQUE ("NAME") ENABLE, 
    FOREIGN KEY ("PARENTCATEGORYID") REFERENCES "AARON_IPT"."CATEGORIES" ("CATEGORYID") ON DELETE CASCADE ENABLE
);

-- Create USERS table
CREATE TABLE "AARON_IPT"."USERS" 
(
    "USERID" NUMBER(*,0), 
    "USERNAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
    "PASSWORDHASH" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
    "EMAIL" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
    "ROLE" VARCHAR2(50 BYTE) DEFAULT 'Customer', 
    "LASTLOGIN" DATE, 
    "DATECREATED" DATE DEFAULT SYSDATE, 
    "DATEMODIFIED" DATE DEFAULT SYSDATE, 
    "ISACTIVE" NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY ("USERID") ENABLE, 
    UNIQUE ("USERNAME") ENABLE, 
    UNIQUE ("EMAIL") ENABLE
);

-- Create PRODUCTS table
CREATE TABLE "AARON_IPT"."PRODUCTS" 
(
    "PRODUCTID" NUMBER(*,0), 
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
    "DESCRIPTION" VARCHAR2(4000 BYTE), 
    "PRICE" NUMBER(10,2) NOT NULL ENABLE, 
    "STOCKQUANTITY" NUMBER(*,0) NOT NULL ENABLE, 
    "IMAGE" BLOB, 
    "ISLATEST" NUMBER(1,0) DEFAULT 0, 
    "DATECREATED" DATE DEFAULT SYSDATE, 
    "DATEMODIFIED" DATE DEFAULT SYSDATE, 
    "ISACTIVE" NUMBER(1,0) DEFAULT 1,
    PRIMARY KEY ("PRODUCTID") ENABLE, 
    UNIQUE ("NAME") ENABLE
);

-- Create ORDERS table
CREATE TABLE "AARON_IPT"."ORDERS" 
(
    "ORDERID" NUMBER, 
    "USERID" NUMBER NOT NULL ENABLE, 
    "ORDERDATE" DATE DEFAULT SYSDATE, 
    "TOTALAMOUNT" NUMBER(10,2) NOT NULL ENABLE, 
    "ISACTIVE" NUMBER(1,0) DEFAULT 1, 
    "STATUS" VARCHAR2(20 BYTE) DEFAULT 'Pending' NOT NULL ENABLE, 
    PRIMARY KEY ("ORDERID") ENABLE, 
    FOREIGN KEY ("USERID") REFERENCES "AARON_IPT"."USERS" ("USERID") ON DELETE CASCADE ENABLE
);

-- Add comment for ORDER STATUS
COMMENT ON COLUMN "AARON_IPT"."ORDERS"."STATUS" IS 'Order status (Pending, Processing, Shipped, Delivered, Cancelled)';

-- Create index for ORDER STATUS
CREATE INDEX "AARON_IPT"."IDX_ORDERS_STATUS" ON "AARON_IPT"."ORDERS" ("STATUS");

-- Create PRODUCTCATEGORIES table (junction table)
CREATE TABLE "AARON_IPT"."PRODUCTCATEGORIES" 
(
    "PRODUCTCATEGORYID" NUMBER(*,0), 
    "PRODUCTID" NUMBER(*,0) NOT NULL ENABLE, 
    "CATEGORYID" NUMBER(*,0) NOT NULL ENABLE, 
    PRIMARY KEY ("PRODUCTCATEGORYID") ENABLE, 
    FOREIGN KEY ("PRODUCTID") REFERENCES "AARON_IPT"."PRODUCTS" ("PRODUCTID") ON DELETE CASCADE ENABLE, 
    FOREIGN KEY ("CATEGORYID") REFERENCES "AARON_IPT"."CATEGORIES" ("CATEGORYID") ON DELETE CASCADE ENABLE
);

-- Create ORDERDETAILS table
CREATE TABLE "AARON_IPT"."ORDERDETAILS" 
(
    "ORDERDETAILID" NUMBER, 
    "ORDERID" NUMBER NOT NULL ENABLE, 
    "PRODUCTID" NUMBER NOT NULL ENABLE, 
    "QUANTITY" NUMBER(*,0) NOT NULL ENABLE, 
    "PRICE" NUMBER(10,2) NOT NULL ENABLE, 
    "ISACTIVE" NUMBER(1,0) DEFAULT 1, 
    PRIMARY KEY ("ORDERDETAILID") ENABLE, 
    FOREIGN KEY ("ORDERID") REFERENCES "AARON_IPT"."ORDERS" ("ORDERID") ON DELETE CASCADE ENABLE, 
    FOREIGN KEY ("PRODUCTID") REFERENCES "AARON_IPT"."PRODUCTS" ("PRODUCTID") ON DELETE CASCADE ENABLE
);

-- Create sequences for auto-increment columns
CREATE SEQUENCE "AARON_IPT"."CATEGORIES_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "AARON_IPT"."USERS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "AARON_IPT"."PRODUCTS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "AARON_IPT"."ORDERS_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "AARON_IPT"."PRODUCTCATEGORIES_SEQ" START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE "AARON_IPT"."ORDERDETAILS_SEQ" START WITH 1 INCREMENT BY 1;

-- Create triggers for auto-increment IDs
CREATE OR REPLACE TRIGGER "AARON_IPT"."CATEGORIES_TRIGGER" 
BEFORE INSERT ON CATEGORIES
FOR EACH ROW
BEGIN
    SELECT CATEGORIES_SEQ.NEXTVAL INTO :NEW.CATEGORYID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER "AARON_IPT"."USERS_TRIGGER" 
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.USERID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER "AARON_IPT"."PRODUCTS_TRIGGER" 
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.PRODUCTID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;
/

CREATE OR REPLACE TRIGGER "AARON_IPT"."ORDERS_TRIGGER" 
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    SELECT ORDERS_SEQ.NEXTVAL INTO :NEW.ORDERID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "AARON_IPT"."PRODUCTCATEGORIES_TRIGGER" 
BEFORE INSERT ON PRODUCTCATEGORIES
FOR EACH ROW
BEGIN
    SELECT PRODUCTCATEGORIES_SEQ.NEXTVAL INTO :NEW.PRODUCTCATEGORYID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER "AARON_IPT"."ORDERDETAILS_TRIGGER" 
BEFORE INSERT ON ORDERDETAILS
FOR EACH ROW
BEGIN
    SELECT ORDERDETAILS_SEQ.NEXTVAL INTO :NEW.ORDERDETAILID FROM DUAL;
END;
/

-- Commit all changes
COMMIT; 