--------------------------------------------------------
--  DDL for Trigger CATEGORIES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."CATEGORIES_TRIGGER" 
BEFORE INSERT ON "AARON_IPT"."CATEGORIES"
FOR EACH ROW
BEGIN
    SELECT "AARON_IPT"."CATEGORIES_SEQ".NEXTVAL INTO :NEW.CATEGORYID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;

/
ALTER TRIGGER "AARON_IPT"."CATEGORIES_TRIGGER" ENABLE;
