--------------------------------------------------------
--  DDL for View DASHBOARD_REVENUE_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "AARON_IPT"."DASHBOARD_REVENUE_VIEW" ("ORDER_DATE", "ORDER_COUNT", "TOTAL_REVENUE", "PENDING_COUNT", "PENDING_REVENUE", "APPROVED_COUNT", "APPROVED_REVENUE") AS 
  SELECT 
    TRUNC(o.ORDERDATE) AS ORDER_DATE,
    COUNT(DISTINCT o.ORDERID) AS ORDER_COUNT,
    SUM(od.PRICE) AS TOTAL_REVENUE,
    COUNT(DISTINCT CASE WHEN o.STATUS = 'Pending' THEN o.ORDERID END) AS PENDING_COUNT,
    SUM(CASE WHEN o.STATUS = 'Pending' THEN od.PRICE ELSE 0 END) AS PENDING_REVENUE,
    COUNT(DISTINCT CASE WHEN o.STATUS = 'Approved' THEN o.ORDERID END) AS APPROVED_COUNT,
    SUM(CASE WHEN o.STATUS = 'Approved' THEN od.PRICE ELSE 0 END) AS APPROVED_REVENUE
FROM 
    ORDERS o
JOIN 
    ORDERDETAILS od ON o.ORDERID = od.ORDERID
WHERE 
    o.ISACTIVE = 1
    AND od.ISACTIVE = 1
GROUP BY 
    TRUNC(o.ORDERDATE)
;
