--------------------------------------------------------
--  File created - Sunday-April-06-2025   
--------------------------------------------------------
@C:\Users\aaron\Downloads\latest\BLOGS_SEQ.sql
@C:\Users\aaron\Downloads\latest\CATEGORIES_SEQ.sql
@C:\Users\aaron\Downloads\latest\CONTACTMESSAGES_SEQ.sql
@C:\Users\aaron\Downloads\latest\NEWSLETTER_SEQ.sql
@C:\Users\aaron\Downloads\latest\ORDERDETAILS_SEQ.sql
@C:\Users\aaron\Downloads\latest\ORDERS_SEQ.sql
@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES_SEQ.sql
@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS_SEQ.sql
@C:\Users\aaron\Downloads\latest\PRODUCTS_SEQ.sql
@C:\Users\aaron\Downloads\latest\SETTINGS_SEQ.sql
@C:\Users\aaron\Downloads\latest\SHOP_SETTINGS_SEQ.sql
@C:\Users\aaron\Downloads\latest\USERS_SEQ.sql
@C:\Users\aaron\Downloads\latest\VOUCHERS_SEQ.sql
@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE_SEQ.sql
@C:\Users\aaron\Downloads\latest\WISHLIST_SEQ.sql
@C:\Users\aaron\Downloads\latest\BLOGS.sql
@C:\Users\aaron\Downloads\latest\CATEGORIES.sql
@C:\Users\aaron\Downloads\latest\CONTACTMESSAGES.sql
@C:\Users\aaron\Downloads\latest\NEWSLETTER.sql
@C:\Users\aaron\Downloads\latest\ORDERDETAILS.sql
@C:\Users\aaron\Downloads\latest\ORDERS.sql
@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES.sql
@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS.sql
@C:\Users\aaron\Downloads\latest\PRODUCTS.sql
@C:\Users\aaron\Downloads\latest\SETTINGS.sql
@C:\Users\aaron\Downloads\latest\SHOP_SETTINGS.sql
@C:\Users\aaron\Downloads\latest\USERS.sql
@C:\Users\aaron\Downloads\latest\VOUCHERS.sql
@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE.sql
@C:\Users\aaron\Downloads\latest\WISHLIST.sql
@C:\Users\aaron\Downloads\latest\DASHBOARD_REVENUE_VIEW.sql
@C:\Users\aaron\Downloads\latest\REVENUE_SUMMARY.sql
--@C:\Users\aaron\Downloads\latest\BLOGS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\CATEGORIES_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\CONTACTMESSAGES_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\NEWSLETTER_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\ORDERDETAILS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\ORDERS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\PRODUCTS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\SETTINGS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\SHOP_SETTINGS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\USERS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\VOUCHERS_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\WISHLIST_DATA_TABLE.tsv
--@C:\Users\aaron\Downloads\latest\DASHBOARD_REVENUE_VIEW_DATA_VIEW.tsv
--@C:\Users\aaron\Downloads\latest\REVENUE_SUMMARY_DATA_VIEW.tsv
@C:\Users\aaron\Downloads\latest\IDX_ORDERS_USER.sql
@C:\Users\aaron\Downloads\latest\IDX_ORDERS_STATUS_DATE.sql
@C:\Users\aaron\Downloads\latest\IDX_PRODUCTS_NEW.sql
@C:\Users\aaron\Downloads\latest\IDX_ORDER_DETAILS_PRODUCT.sql
@C:\Users\aaron\Downloads\latest\IDX_ORDERS_STATUS.sql
@C:\Users\aaron\Downloads\latest\IDX_ORDERS_DATE.sql
@C:\Users\aaron\Downloads\latest\IDX_PRODUCTS_FEATURED.sql
@C:\Users\aaron\Downloads\latest\CATEGORIES_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\NEWSLETTER_TRG.sql
@C:\Users\aaron\Downloads\latest\ORDERDETAILS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\ORDERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS_TRG.sql
@C:\Users\aaron\Downloads\latest\PRODUCTS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\SETTINGS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\SHOP_SETTINGS_UPDATE_TRG.sql
@C:\Users\aaron\Downloads\latest\TRG_ORDER_STATUS_TRACK.sql
@C:\Users\aaron\Downloads\latest\TRG_PRODUCT_STOCK_CHECK.sql
@C:\Users\aaron\Downloads\latest\TRG_UPDATE_ORDER_TOTAL.sql
@C:\Users\aaron\Downloads\latest\USERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\VOUCHERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\VOUCHERS_UPDATE_TRG.sql
@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE_TRIGGER.sql
@C:\Users\aaron\Downloads\latest\WISHLIST_TRG.sql
@C:\Users\aaron\Downloads\latest\APPROVE_ORDER.sql
@C:\Users\aaron\Downloads\latest\CALCULATE_DASHBOARD_REVENUE.sql
@C:\Users\aaron\Downloads\latest\CALCULATE_REVENUE_STATS.sql
@C:\Users\aaron\Downloads\latest\CALC_REVENUE.sql
@C:\Users\aaron\Downloads\latest\GET_INVENTORY_ALERTS.sql
@C:\Users\aaron\Downloads\latest\GET_INVENTORY_ALERTS_V2.sql
@C:\Users\aaron\Downloads\latest\PRC_CALCULATE_ORDER_COMPARISON.sql
@C:\Users\aaron\Downloads\latest\PRC_CALC_REVENUE_COMP.sql
@C:\Users\aaron\Downloads\latest\PRC_CREATE_ORDER.sql
@C:\Users\aaron\Downloads\latest\PRC_GET_DASHBOARD_PREFERENCES.sql
@C:\Users\aaron\Downloads\latest\PRC_PRODUCT_ADD.sql
@C:\Users\aaron\Downloads\latest\PRC_PRODUCT_RATE.sql
@C:\Users\aaron\Downloads\latest\PRC_PRODUCT_UPDATE_STOCK.sql
@C:\Users\aaron\Downloads\latest\PRC_SAVE_DASHBOARD_PREFERENCES.sql
@C:\Users\aaron\Downloads\latest\PRC_UPDATE_ORDER_STATUS.sql
@C:\Users\aaron\Downloads\latest\PRC_USER_LOGIN.sql
@C:\Users\aaron\Downloads\latest\PRC_USER_REGISTER.sql
@C:\Users\aaron\Downloads\latest\PRC_USER_RESET_PASSWORD.sql
@C:\Users\aaron\Downloads\latest\CALCULATE_REVENUE_STATS2.sql
@C:\Users\aaron\Downloads\latest\GET_RECENT_ACTIVITY.sql
@C:\Users\aaron\Downloads\latest\GET_REVENUE_BY_TIMEFRAME.sql
@C:\Users\aaron\Downloads\latest\GET_REVENUE_SUMMARY.sql
@C:\Users\aaron\Downloads\latest\GET_SALES_BY_CATEGORY.sql
@C:\Users\aaron\Downloads\latest\GET_TOP_SELLING_PRODUCTS.sql
@C:\Users\aaron\Downloads\latest\GET_TOTAL_REVENUE.sql
@C:\Users\aaron\Downloads\latest\CATEGORIES_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\SETTINGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\ORDERDETAILS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\NEWSLETTER_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\USERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\WISHLIST_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\BLOGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\ORDERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\SHOP_SETTINGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\CONTACTMESSAGES_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\PRODUCTS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\VOUCHERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\BLOGS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\CATEGORIES_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\CONTACTMESSAGES_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\NEWSLETTER_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\ORDERDETAILS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\ORDERS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\PRODUCTCATEGORIES_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\PRODUCTRATINGS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\VOUCHERUSAGE_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latest\WISHLIST_REFCONSTRAINT.sql
