--------------------------------------------------------
--  File created - Monday-April-07-2025   
--------------------------------------------------------
@C:\Users\aaron\Downloads\latesttt\BLOGS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\CATEGORIES_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\CONTACTMESSAGES_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\NEWSLETTER_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\ORDERS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\SETTINGS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\SHOP_SETTINGS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\USERS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERS_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\WISHLIST_SEQ.sql
@C:\Users\aaron\Downloads\latesttt\CATEGORIES.sql
@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS.sql
@C:\Users\aaron\Downloads\latesttt\ORDERS.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTS.sql
@C:\Users\aaron\Downloads\latesttt\SETTINGS.sql
@C:\Users\aaron\Downloads\latesttt\USERS.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERS.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE.sql
@C:\Users\aaron\Downloads\latesttt\WISHLIST.sql
@C:\Users\aaron\Downloads\latesttt\DASHBOARD_REVENUE_VIEW.sql
@C:\Users\aaron\Downloads\latesttt\REVENUE_SUMMARY.sql
--@C:\Users\aaron\Downloads\latesttt\CATEGORIES_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\ORDERS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\PRODUCTS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\SETTINGS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\USERS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\VOUCHERS_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\WISHLIST_DATA_TABLE.csv
--@C:\Users\aaron\Downloads\latesttt\DASHBOARD_REVENUE_VIEW_DATA_VIEW.csv
--@C:\Users\aaron\Downloads\latesttt\REVENUE_SUMMARY_DATA_VIEW.csv
@C:\Users\aaron\Downloads\latesttt\IDX_ORDER_DETAILS_PRODUCT.sql
@C:\Users\aaron\Downloads\latesttt\IDX_ORDERS_USER.sql
@C:\Users\aaron\Downloads\latesttt\IDX_ORDERS_STATUS_DATE.sql
@C:\Users\aaron\Downloads\latesttt\IDX_ORDERS_STATUS.sql
@C:\Users\aaron\Downloads\latesttt\IDX_ORDERS_DATE.sql
@C:\Users\aaron\Downloads\latesttt\IDX_PRODUCTS_FEATURED.sql
@C:\Users\aaron\Downloads\latesttt\CATEGORIES_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\ORDERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS_TRG.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\SETTINGS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\TRG_ORDER_STATUS_TRACK.sql
@C:\Users\aaron\Downloads\latesttt\TRG_PRODUCT_STOCK_CHECK.sql
@C:\Users\aaron\Downloads\latesttt\TRG_UPDATE_ORDER_TOTAL.sql
@C:\Users\aaron\Downloads\latesttt\USERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERS_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE_TRIGGER.sql
@C:\Users\aaron\Downloads\latesttt\WISHLIST_TRG.sql
@C:\Users\aaron\Downloads\latesttt\APPROVE_ORDER.sql
@C:\Users\aaron\Downloads\latesttt\CALCULATE_DASHBOARD_REVENUE.sql
@C:\Users\aaron\Downloads\latesttt\CALCULATE_REVENUE_STATS.sql
@C:\Users\aaron\Downloads\latesttt\CALC_REVENUE.sql
@C:\Users\aaron\Downloads\latesttt\GET_INVENTORY_ALERTS.sql
@C:\Users\aaron\Downloads\latesttt\GET_INVENTORY_ALERTS_V2.sql
@C:\Users\aaron\Downloads\latesttt\PRC_CALCULATE_ORDER_COMPARISON.sql
@C:\Users\aaron\Downloads\latesttt\PRC_CALC_REVENUE_COMP.sql
@C:\Users\aaron\Downloads\latesttt\PRC_CREATE_ORDER.sql
@C:\Users\aaron\Downloads\latesttt\PRC_GET_DASHBOARD_PREFERENCES.sql
@C:\Users\aaron\Downloads\latesttt\PRC_PRODUCT_ADD.sql
@C:\Users\aaron\Downloads\latesttt\PRC_PRODUCT_RATE.sql
@C:\Users\aaron\Downloads\latesttt\PRC_PRODUCT_UPDATE_STOCK.sql
@C:\Users\aaron\Downloads\latesttt\PRC_SAVE_DASHBOARD_PREFERENCES.sql
@C:\Users\aaron\Downloads\latesttt\PRC_UPDATE_ORDER_STATUS.sql
@C:\Users\aaron\Downloads\latesttt\PRC_USER_LOGIN.sql
@C:\Users\aaron\Downloads\latesttt\PRC_USER_REGISTER.sql
@C:\Users\aaron\Downloads\latesttt\PRC_USER_RESET_PASSWORD.sql
@C:\Users\aaron\Downloads\latesttt\CALCULATE_REVENUE_STATS2.sql
@C:\Users\aaron\Downloads\latesttt\GET_RECENT_ACTIVITY.sql
@C:\Users\aaron\Downloads\latesttt\GET_REVENUE_BY_TIMEFRAME.sql
@C:\Users\aaron\Downloads\latesttt\GET_REVENUE_SUMMARY.sql
@C:\Users\aaron\Downloads\latesttt\GET_SALES_BY_CATEGORY.sql
@C:\Users\aaron\Downloads\latesttt\GET_TOP_SELLING_PRODUCTS.sql
@C:\Users\aaron\Downloads\latesttt\GET_TOTAL_REVENUE.sql
@C:\Users\aaron\Downloads\latesttt\USERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\CATEGORIES_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\WISHLIST_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\SETTINGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\ORDERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERS_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES_CONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\CATEGORIES_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\ORDERDETAILS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\ORDERS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTCATEGORIES_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\PRODUCTRATINGS_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\VOUCHERUSAGE_REFCONSTRAINT.sql
@C:\Users\aaron\Downloads\latesttt\WISHLIST_REFCONSTRAINT.sql
