--------------------------------------------------------
--  DDL for Index IDX_ORDER_DETAILS_PRODUCT
--------------------------------------------------------

  CREATE INDEX "AARON_IPT"."IDX_ORDER_DETAILS_PRODUCT" ON "AARON_IPT"."ORDERDETAILS" ("PRODUCTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
