--------------------------------------------------------
--  DDL for Trigger ORDERDETAILS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."ORDERDETAILS_TRIGGER" 
BEFORE INSERT ON ORDERDETAILS
FOR EACH ROW
BEGIN
    SELECT ORDERDETAILS_SEQ.NEXTVAL INTO :NEW.ORDERDETAILID FROM DUAL;
END;

/
ALTER TRIGGER "AARON_IPT"."ORDERDETAILS_TRIGGER" ENABLE;
