--------------------------------------------------------
--  Ref Constraints for Table ORDERDETAILS
--------------------------------------------------------

  ALTER TABLE "AARON_IPT"."ORDERDETAILS" ADD CONSTRAINT "FK_ORDERDETAILS_ORDER" FOREIGN KEY ("ORDERID")
	  REFERENCES "AARON_IPT"."ORDERS" ("ORDERID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AARON_IPT"."ORDERDETAILS" ADD CONSTRAINT "FK_ORDERDETAILS_PRODUCT" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "AARON_IPT"."PRODUCTS" ("PRODUCTID") ON DELETE CASCADE ENABLE;
