--------------------------------------------------------
--  DDL for Trigger PRODUCTS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."PRODUCTS_TRIGGER" 
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    SELECT PRODUCTS_SEQ.NEXTVAL INTO :NEW.PRODUCTID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;

/
ALTER TRIGGER "AARON_IPT"."PRODUCTS_TRIGGER" ENABLE;
