--------------------------------------------------------
--  DDL for Trigger PRODUCTCATEGORIES_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."PRODUCTCATEGORIES_TRIGGER" 
BEFORE INSERT ON PRODUCTCATEGORIES
FOR EACH ROW
BEGIN
    SELECT PRODUCTCATEGORIES_SEQ.NEXTVAL INTO :NEW.PRODUCTCATEGORYID FROM DUAL;
END;

/
ALTER TRIGGER "AARON_IPT"."PRODUCTCATEGORIES_TRIGGER" ENABLE;
