--------------------------------------------------------
--  Ref Constraints for Table PRODUCTCATEGORIES
--------------------------------------------------------

  ALTER TABLE "AARON_IPT"."PRODUCTCATEGORIES" ADD FOREIGN KEY ("PRODUCTID")
	  REFERENCES "AARON_IPT"."PRODUCTS" ("PRODUCTID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AARON_IPT"."PRODUCTCATEGORIES" ADD FOREIGN KEY ("CATEGORYID")
	  REFERENCES "AARON_IPT"."CATEGORIES" ("CATEGORYID") ON DELETE CASCADE ENABLE;
