--------------------------------------------------------
--  Ref Constraints for Table PRODUCTRATINGS
--------------------------------------------------------

  ALTER TABLE "AARON_IPT"."PRODUCTRATINGS" ADD CONSTRAINT "FK_RATINGS_PRODUCT" FOREIGN KEY ("PRODUCTID")
	  REFERENCES "AARON_IPT"."PRODUCTS" ("PRODUCTID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "AARON_IPT"."PRODUCTRATINGS" ADD CONSTRAINT "FK_RATINGS_USER" FOREIGN KEY ("USERID")
	  REFERENCES "AARON_IPT"."USERS" ("USERID") ON DELETE CASCADE ENABLE;
