--------------------------------------------------------
--  DDL for View REVENUE_SUMMARY
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "AARON_IPT"."REVENUE_SUMMARY" ("TIME_RANGE", "REVENUE") AS 
  SELECT
    'today' AS TIME_RANGE,
    NVL(SUM(OD.PRICE * OD.QUANTITY - NVL(OD.COSTPRICE, 0) * OD.QUANTITY), 0) AS REVENUE
FROM
    ORDERS O
JOIN
    ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE
    TRUNC(O.ORDERDATE) = TRUNC(SYSDATE)
AND
    O.STATUS IN ('Completed', 'Approved', 'Delivered', 'Shipped', 'Processing')
UNION ALL
SELECT
    'yesterday' AS TIME_RANGE,
    NVL(SUM(OD.PRICE * OD.QUANTITY - NVL(OD.COSTPRICE, 0) * OD.QUANTITY), 0) AS REVENUE
FROM
    ORDERS O
JOIN
    ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE
    TRUNC(O.ORDERDATE) = TRUNC(SYSDATE) - 1
AND
    O.STATUS IN ('Completed', 'Approved', 'Delivered', 'Shipped', 'Processing')
UNION ALL
SELECT
    'week' AS TIME_RANGE,
    NVL(SUM(OD.PRICE * OD.QUANTITY - NVL(OD.COSTPRICE, 0) * OD.QUANTITY), 0) AS REVENUE
FROM
    ORDERS O
JOIN
    ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE
    O.ORDERDATE >= TRUNC(SYSDATE) - 7
AND
    O.STATUS IN ('Completed', 'Approved', 'Delivered', 'Shipped', 'Processing')
UNION ALL
SELECT
    'month' AS TIME_RANGE,
    NVL(SUM(OD.PRICE * OD.QUANTITY - NVL(OD.COSTPRICE, 0) * OD.QUANTITY), 0) AS REVENUE
FROM
    ORDERS O
JOIN
    ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
WHERE
    O.ORDERDATE >= TRUNC(SYSDATE) - 30
AND
    O.STATUS IN ('Completed', 'Approved', 'Delivered', 'Shipped', 'Processing')
;
