--------------------------------------------------------
--  DDL for Trigger SETTINGS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."SETTINGS_TRIGGER" 
BEFORE INSERT ON AARON_IPT.SETTINGS
FOR EACH ROW
BEGIN
  SELECT AARON_IPT.SETTINGS_SEQ.NEXTVAL INTO :NEW.SETTINGID FROM DUAL;
  :NEW.DATECREATED := SYSDATE;
  :NEW.DATEMODIFIED := SYSDATE;
END;

/
ALTER TRIGGER "AARON_IPT"."SETTINGS_TRIGGER" ENABLE;
