--------------------------------------------------------
--  DDL for Table SHOP_SETTINGS
--------------------------------------------------------

  CREATE TABLE "AARON_IPT"."SHOP_SETTINGS" 
   (	"SETTING_ID" NUMBER, 
	"SETTING_KEY" VARCHAR2(100 BYTE), 
	"SETTING_VALUE" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"MODIFIED_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
