--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCT_STOCK_CHECK
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."TRG_PRODUCT_STOCK_CHECK" 
   AFTER UPDATE OF STOCKQUANTITY ON PRODUCTS
   FOR EACH ROW
   BEGIN
     IF :NEW.STOCKQUANTITY <= :NEW.LOWSTOCKTHRESHOLD THEN
       INSERT INTO STOCKALERTS (PRODUCTID, ALERTDATE, STOCKLEVEL, ISRESOLVED)
       VALUES (:NEW.PRODUCTID, SYSDATE, :NEW.STOCKQUANTITY, 0);
     END IF;
   END;

/
ALTER TRIGGER "AARON_IPT"."TRG_PRODUCT_STOCK_CHECK" ENABLE;
