--------------------------------------------------------
--  DDL for Trigger TRG_UPDATE_ORDER_TOTAL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."TRG_UPDATE_ORDER_TOTAL" 
AFTER INSERT OR UPDATE OR DELETE ON ORDERDETAILS
FOR EACH ROW
BEGIN
    -- Use separate IF statements instead of complex CASE expressions
    IF INSERTING THEN
        UPDATE ORDERS SET TOTALAMOUNT = TOTALAMOUNT + (:NEW.PRICE * :NEW.QUANTITY)
        WHERE ORDERID = :NEW.ORDERID;
    ELSIF UPDATING THEN
        UPDATE ORDERS SET TOTALAMOUNT = TOTALAMOUNT + (:NEW.PRICE * :NEW.QUANTITY) - (:OLD.PRICE * :OLD.QUANTITY)
        WHERE ORDERID = :NEW.ORDERID;
    ELSIF DELETING THEN
        UPDATE ORDERS SET TOTALAMOUNT = TOTALAMOUNT - (:OLD.PRICE * :OLD.QUANTITY)
        WHERE ORDERID = :OLD.ORDERID;
    END IF;
END;

/
ALTER TRIGGER "AARON_IPT"."TRG_UPDATE_ORDER_TOTAL" ENABLE;
