--------------------------------------------------------
--  DDL for Trigger USERS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."USERS_TRIGGER" 
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
    SELECT USERS_SEQ.NEXTVAL INTO :NEW.USERID FROM DUAL;
    :NEW.DATECREATED := SYSDATE;
    :NEW.DATEMODIFIED := SYSDATE;
END;

/
ALTER TRIGGER "AARON_IPT"."USERS_TRIGGER" ENABLE;
