--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "AARON_IPT"."USERS" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"PASSWORDHASH" VARCHAR2(4000 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'Customer', 
	"LASTLOGIN" DATE, 
	"DATECREATED" DATE DEFAULT SYSDATE, 
	"DATEMODIFIED" DATE DEFAULT SYSDATE, 
	"ISACTIVE" NUMBER(1,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
