--------------------------------------------------------
--  DDL for Trigger VOUCHERS_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."VOUCHERS_TRIGGER" 
BEFORE INSERT ON AARON_IPT.VOUCHERS
FOR EACH ROW
BEGIN
  SELECT AARON_IPT.VOUCHERS_SEQ.NEXTVAL INTO :NEW.VOUCHERID FROM DUAL;
  :NEW.DATECREATED := SYSDATE;
  :NEW.DATEMODIFIED := SYSDATE;
END;

/
ALTER TRIGGER "AARON_IPT"."VOUCHERS_TRIGGER" ENABLE;
