--------------------------------------------------------
--  DDL for Trigger VOUCHERUSAGE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."VOUCHERUSAGE_TRIGGER" 
BEFORE INSERT ON VOUCHERUSAGE
FOR EACH ROW
BEGIN
    SELECT VOUCHERUSAGE_SEQ.NEXTVAL INTO :NEW.VOUCHERUSAGEID FROM DUAL;
END;

/
ALTER TRIGGER "AARON_IPT"."VOUCHERUSAGE_TRIGGER" ENABLE;
