--------------------------------------------------------
--  Ref Constraints for Table VOUCHERUSAGE
--------------------------------------------------------

  ALTER TABLE "AARON_IPT"."VOUCHERUSAGE" ADD CONSTRAINT "FK_VOUCHERUSAGE_ORDER" FOREIGN KEY ("ORDERID")
	  REFERENCES "AARON_IPT"."ORDERS" ("ORDERID") ENABLE;
  ALTER TABLE "AARON_IPT"."VOUCHERUSAGE" ADD CONSTRAINT "FK_VOUCHERUSAGE_USER" FOREIGN KEY ("USERID")
	  REFERENCES "AARON_IPT"."USERS" ("USERID") ENABLE;
  ALTER TABLE "AARON_IPT"."VOUCHERUSAGE" ADD CONSTRAINT "FK_VOUCHERUSAGE_VOUCHER" FOREIGN KEY ("VOUCHERID")
	  REFERENCES "AARON_IPT"."VOUCHERS" ("VOUCHERID") ENABLE;
