--------------------------------------------------------
--  DDL for Trigger VOUCHERUSAGE_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "AARON_IPT"."VOUCHERUSAGE_TRIGGER" 
BEFORE INSERT ON AARON_IPT.VOUCHERUSAGE
FOR EACH ROW
BEGIN
  SELECT AARON_IPT.VOUCHERUSAGE_SEQ.NEXTVAL INTO :NEW.VOUCHERUSAGEID FROM DUAL;
END;

/
ALTER TRIGGER "AARON_IPT"."VOUCHERUSAGE_TRIGGER" ENABLE;
